Token authentication
lucasrcdias/viewpoint pull request #10
Opened 2016-10-25 10:29 UTC by viniciuslopeslps

Usando token de autenticação para requisições

2016-10-26 11:58 UTC, lucasrcdias commented on viewpoint-api/db.txt
> +api_key varchar(500) not null unique,
Pq precisou mudar?

2016-10-26 11:58 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/ErrorResponse.java
> +        this.setField(field);
Cada um de um jeito, poderia padronizar eu acho.

Um usa o setter outro não..

2016-10-26 11:58 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/configuration/BeanConfiguration.java
> +
Linha sobrando ,rs

2016-10-26 11:58 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/model/entity/User.java
> +    @Length(max = 500)
A chave de API precisou mudar mesmo?

2016-10-26 12:07 UTC, lucasrcdias commented
Pelo que conversamos:

O campo API_KEY do banco é API_KEY e será armazenado o hash do e-mail do usuário;
Não é necessário salvar o token gerado pelo JWT.
Buscar o usuário pelo e-mail ou id inserido no payload do token.

2016-10-27 14:03 UTC, lucasrcdias requested changes

2016-10-27 14:03 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/service/UserService.java
>              user.setEmail(password);
Aqui seria setPassword, não?

2016-10-27 14:03 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/service/UserService.java
>              user.setEmail(name);
E aqui setName, correto?

2016-10-27 14:03 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/service/UserService.java
> +            user.setKey(jwtUtils.generateToken(user));
Se fizer isso não vai salvar o jwt token no api key?

2016-10-27 23:33 UTC, viniciuslopeslps commented on viewpoint-api/viewpoint/src/main/java/br/com/service/UserService.java
> +            user.setKey(jwtUtils.generateToken(user));
@lucasrcdias quando você anota um campo @Transient ele não salva no banco (como fiz no user)

2016-10-29 15:27 UTC, merged