melhorando retorno de respostas de erro da api
lucasrcdias/viewpoint pull request #9
Opened 2016-10-21 11:29 UTC by viniciuslopeslps

2016-10-22 19:42 UTC, lucasrcdias requested changes
Só comentários sobre as mensagens de erro em sí, o restante acho que tá ok!

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/controller/UserDTO.java
> +    @NotEmpty(message = "O campo de email não deveria ser vazio")
Sugestão de mensagem: "O preenchimento do e-mail é obrigatório"

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/controller/UserDTO.java
> +    @Email(message = "o campo de email não está em um formato correto")
Sugestão: "O e-mail informado não é válido"

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/controller/UserDTO.java
> +    @Length(max = 254, message = "O campo de email deve ter o tamanho até 254 caracteres")
Sugestão: "O e-mail pode conter no máximo 254 caracteres"

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/controller/UserDTO.java
> +    @Length(min = 6, message = "O campo de senha deve ter o tamanho de no minimo 6 caracteres")
Sugestão: "A senha deve conter no mínimo 6 caracteres"

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/controller/UserDTO.java
> +    @NotEmpty(message = "o campo de senha não deveria ser vazio")
Sugestão: "O preenchimento da senha é obrigatório"

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/controller/UserDTO.java
> +    @Length(max = 254, message = "O campo de naome deve ter o tamanho até 60 caracteres")
Na anotação você diz: `max = 254` mas na mensagem de erro diz "60".
Nome está escrito errado.

Sugestão: "O nome deve conter no máximo 60 caracteres".

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/controller/UserDTO.java
> +    @NotEmpty(message = "O campo nome não deveria ser vazio")
Sugestão: "O preenchimento do nome é obrigatório"

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/model/entity/User.java
> +    @NotEmpty(message = "O campo email não deveria ser vazio")
A mensagem tem que estar nos dois lugares? Ví elas na classe `UserDTO` e nessa aqui.

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/service/UserService.java
> +            throw new BusinessException(HttpStatus.ALREADY_REPORTED, "the user has already registered");
Essa mensagem poderia estar em português também, sugestão: "O e-mail informado já está em uso, utilize o link para recuperação de senha."

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/service/UserService.java
> +            throw new BusinessException(HttpStatus.NOT_FOUND, "User not found by id");
Poderia já estar em pt, sugestão: "Usuário não encontrado."

2016-10-22 19:42 UTC, lucasrcdias commented on viewpoint-api/viewpoint/src/main/java/br/com/service/UserService.java
> +            throw new BusinessException(HttpStatus.NOT_FOUND, "User not found by id");
O mesmo do de cima!

2016-10-23 16:56 UTC, viniciuslopeslps commented on viewpoint-api/viewpoint/src/main/java/br/com/model/entity/User.java
> +    @NotEmpty(message = "O campo email não deveria ser vazio")
@lucasrcdias um é para validação do que o client está passando, o outro é uma validação da entidade (usada para salvar no banco e etc).

Imagina que pode acontecer do client enviar corretamente, cair no service e lá existir um método que faça com que um campo fique inválido (exemplo: alguém crie um método que deixe a senha com 2 caracteres, na hora de salvar no banco vai estourar um erro com uma mensagem que não temos "controle"), entendeu?

2016-10-23 17:05 UTC, lucasrcdias approved these changes

2016-10-24 10:52 UTC, merged